# Generated by Django 5.0.7 on 2024-07-12 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_anna', '0004_achievement_studentachievement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdfmodel',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы '},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='pdfmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время загрузки файла '),
            preserve_default=False,
        ),
    ]
