# Generated by Django 5.0.7 on 2024-07-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_anna', '0007_photoreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photoreview',
            options={'verbose_name_plural': 'Фото отзывов'},
        ),
        migrations.AddField(
            model_name='user',
            name='on_the_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
