# Generated by Django 5.0.7 on 2024-07-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_anna', '0005_alter_pdfmodel_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfmodel',
            name='name',
            field=models.TextField(max_length=20),
        ),
    ]
